"""AGENTS.md generator — Universal cross-tool AI configuration standard.

AGENTS.md is the Linux Foundation-stewarded universal standard for AI coding tools.
Adopted by 60,000+ open-source projects. Supported by:
  - OpenAI Codex CLI (primary config)
  - Claude Code (fallback when no CLAUDE.md)
  - Cursor (reads alongside .cursorrules)
  - Gemini CLI
  - Continue.dev, Aider, OpenHands

Reference: https://agents.md/
"""

import os

from vcsx.core.context import ProjectContext
from vcsx.generators.base import BaseGenerator


class AgentsMdGenerator(BaseGenerator):
    """Generator for AGENTS.md — the universal AI coding configuration standard."""

    @property
    def name(self) -> str:
        return "agents-md"

    @property
    def output_files(self) -> list[str]:
        return ["AGENTS.md"]

    def generate_config(self, ctx: ProjectContext, output_dir: str) -> str:
        """Generate AGENTS.md at project root."""
        path = os.path.join(output_dir, "AGENTS.md")
        os.makedirs(output_dir, exist_ok=True)

        content = self._build_agents_md(ctx)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path

    def generate_skills(self, ctx: ProjectContext, output_dir: str) -> list[str]:
        return []

    def generate_hooks(self, ctx: ProjectContext, output_dir: str) -> None:
        return None

    def generate_agents(self, ctx: ProjectContext, output_dir: str) -> list[str]:
        return []

    def generate_scaffold(self, ctx: ProjectContext, output_dir: str) -> list[str]:
        return []

    # ─── Private ─────────────────────────────────────────────────────────────

    def _build_agents_md(self, ctx: ProjectContext) -> str:
        """Build the AGENTS.md content."""
        commands = self._get_commands(ctx)
        style = self._get_code_style(ctx)
        project_notes = self._get_project_notes(ctx)
        forbidden = self._get_forbidden(ctx)

        purpose_block = ""
        if ctx.purpose or ctx.problem:
            lines = []
            if ctx.purpose:
                lines.append(f"**Purpose:** {ctx.purpose}")
            if ctx.problem:
                lines.append(f"**Problem Being Solved:** {ctx.problem}")
            if ctx.target_users:
                lines.append(f"**Target Users:** {ctx.target_users}")
            purpose_block = "\n".join(lines) + "\n"

        stack_parts = []
        if ctx.language:
            stack_parts.append(f"**Language:** {ctx.language}")
        if ctx.framework:
            stack_parts.append(f"**Framework:** {ctx.framework}")
        if ctx.tech_stack:
            stack_parts.append(f"**Stack:** {ctx.tech_stack}")
        if ctx.hosting:
            stack_parts.append(f"**Hosting:** {ctx.hosting}")
        stack_block = (
            "\n".join(stack_parts) if stack_parts else "Not specified — infer from codebase."
        )

        return f"""# AGENTS.md — AI Coding Configuration

> This file is the universal AI agent configuration following the [AGENTS.md standard](https://agents.md/).
> It is read by: OpenAI Codex CLI, Claude Code (fallback), Cursor, Gemini CLI, Aider, Continue.dev.

## Project
{purpose_block}- **Name:** {ctx.project_name or "Project"}
- **Type:** {ctx.project_type or "general"}
- **Description:** {ctx.description or "No description provided."}

## Tech Stack
{stack_block}

## Build & Test Commands
{commands}

## Code Style & Conventions
{style}

{project_notes}

## Forbidden Actions
{forbidden}

## Commit Style
Use conventional commits:
- `feat:` — new feature
- `fix:` — bug fix
- `refactor:` — code change that neither fixes a bug nor adds a feature
- `docs:` — documentation only
- `test:` — adding or correcting tests
- `chore:` — tooling, dependencies, CI

## Agent Behavior
- **Read before editing.** Understand the existing pattern before making changes.
- **One task at a time.** Don't mix unrelated changes in one session.
- **Verify assumptions.** If unsure about intent, check git history or ask.
- **Leave code better.** Fix obvious issues you encounter, but don't scope-creep.
- **Tests are required.** New functionality must have tests.

---
*Generated by [vcsx](https://github.com/barancanercan/vcsx)*
"""

    def _get_commands(self, ctx: ProjectContext) -> str:
        lang = ctx.language.lower() if ctx.language else ""
        framework = (ctx.framework or "").lower()
        test_fw = ctx.test_framework or ""

        if lang == "python":
            install = (
                "pip install -e '.[dev]'"
                if "pyproject" in framework or not framework
                else "pip install -r requirements.txt"
            )
            test_cmd = "pytest" if not test_fw or test_fw == "pytest" else test_fw
            fmt = f"{ctx.formatter}" if ctx.formatter else "ruff format ."
            lint = f"{ctx.linter}" if ctx.linter else "ruff check ."
            return f"""```bash
# Install
{install}

# Run tests
{test_cmd}

# Format
{fmt}

# Lint
{lint}
```"""

        if lang in ("typescript", "javascript"):
            pkg = "pnpm" if "pnpm" in (ctx.tech_stack or "").lower() else "npm"
            test_cmd = f"{pkg} test" if not test_fw else test_fw
            return f"""```bash
# Install
{pkg} install

# Dev server
{pkg} run dev

# Run tests
{test_cmd}

# Build
{pkg} run build

# Lint
{pkg} run lint
```"""

        if lang == "go":
            return """```bash
# Build
go build ./...

# Test
go test ./...

# Lint
golangci-lint run

# Format
gofmt -w .
```"""

        if lang == "rust":
            return """```bash
# Build
cargo build

# Test
cargo test

# Lint
cargo clippy

# Format
cargo fmt
```"""

        # Generic fallback
        fmt_line = f"# Format: {ctx.formatter}" if ctx.formatter else ""
        lint_line = f"# Lint: {ctx.linter}" if ctx.linter else ""
        test_line = f"# Test: {ctx.test_framework}" if ctx.test_framework else ""
        lines = [ln for ln in [fmt_line, lint_line, test_line] if ln]
        if lines:
            return "```bash\n" + "\n".join(lines) + "\n```"
        return "*(Commands not specified — infer from project tooling)*"

    def _get_code_style(self, ctx: ProjectContext) -> str:
        lines = []
        if ctx.code_style:
            lines.append(f"- Follow the project's code style: {ctx.code_style}")
        if ctx.formatter:
            lines.append(f"- Format with `{ctx.formatter}` before committing.")
        if ctx.linter:
            lines.append(f"- Run `{ctx.linter}` and resolve all warnings.")

        lang = (ctx.language or "").lower()
        if lang == "python":
            lines += [
                "- Use type hints on all public functions.",
                "- Prefer `pathlib.Path` over `os.path`.",
                "- Use `dataclasses` or `pydantic` for structured data.",
                "- Docstrings on all public functions and classes.",
            ]
        elif lang in ("typescript", "javascript"):
            lines += [
                "- Prefer `const` over `let`; avoid `var`.",
                "- Use async/await over raw Promises.",
                "- Explicit return types on all functions (TypeScript).",
            ]

        if ctx.project_type == "api":
            lines += [
                "- REST: use correct HTTP verbs and status codes.",
                "- Validate all input at API boundaries.",
                "- Return consistent error shapes: `{error, message, code}`.",
            ]

        if ctx.project_type == "data-pipeline":
            lines += [
                "- Process data in chunks — never load full datasets into memory.",
                "- Log progress at meaningful intervals.",
                "- Make operations idempotent where possible.",
                "- SQLite: use `PRAGMA journal_mode=WAL; PRAGMA synchronous=OFF;`",
            ]

        return "\n".join(lines) if lines else "- Follow language-standard conventions."

    def _get_project_notes(self, ctx: ProjectContext) -> str:
        sections = []

        if ctx.auth_needed and ctx.auth_method:
            sections.append(f"""## Authentication
- Auth method: {ctx.auth_method}
- Never log tokens, passwords, or session IDs.
- Validate auth on every protected endpoint.""")

        if ctx.external_services:
            sections.append(f"""## External Services
{ctx.external_services}

- Always handle API errors gracefully with retries where appropriate.
- Respect rate limits — use exponential backoff.""")

        if ctx.hosting:
            sections.append(f"""## Deployment
- Target: {ctx.hosting}
- Run the full test suite before any deployment.
- Check environment variables are set correctly in the target environment.""")

        return "\n\n".join(sections)

    def _get_forbidden(self, ctx: ProjectContext) -> str:
        base = [
            "- `rm -rf` on project directories without explicit confirmation.",
            "- `git push --force` without explicit instruction.",
            "- Committing `.env` files or any file containing secrets.",
            "- Installing new global dependencies without noting them in requirements/package.json.",
            "- Modifying database schema migrations already applied to production.",
        ]

        if ctx.forbidden_actions:
            custom = [f"- {a.strip()}" for a in ctx.forbidden_actions.split(",") if a.strip()]
            base = custom + base

        return "\n".join(base)
