"""Gemini CLI generator — GEMINI.md configuration for Google's Gemini CLI."""

import os

from vcsx.core.context import ProjectContext
from vcsx.generators.base import BaseGenerator


class GeminiGenerator(BaseGenerator):
    """Generator for Google Gemini CLI (gemini-cli).

    Produces GEMINI.md — read by Gemini CLI at project root.
    Gemini CLI also reads ~/.gemini/GEMINI.md as global config.

    Key advantage: 1M token context window (free tier).
    """

    @property
    def name(self) -> str:
        return "gemini"

    @property
    def output_files(self) -> list[str]:
        return ["GEMINI.md"]

    def generate_config(self, ctx: ProjectContext, output_dir: str) -> str:
        """Generate GEMINI.md for Gemini CLI."""
        path = os.path.join(output_dir, "GEMINI.md")
        os.makedirs(output_dir, exist_ok=True)

        content = self._build_gemini_md(ctx)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path

    def generate_skills(self, ctx: ProjectContext, output_dir: str) -> list[str]:
        """Gemini CLI uses GEMINI.md only — no separate skills dir."""
        return []

    def generate_hooks(self, ctx: ProjectContext, output_dir: str) -> None:
        """Gemini CLI does not support hooks in the same way."""
        return None

    def generate_agents(self, ctx: ProjectContext, output_dir: str) -> list[str]:
        return []

    def generate_scaffold(self, ctx: ProjectContext, output_dir: str) -> list[str]:
        return []

    # ─── Private ─────────────────────────────────────────────────────────────

    def _build_gemini_md(self, ctx: ProjectContext) -> str:
        lang_line = f"- **Primary Language:** {ctx.language}" if ctx.language else ""
        framework_line = f"- **Framework:** {ctx.framework}" if ctx.framework else ""
        stack_line = f"- **Tech Stack:** {ctx.tech_stack}" if ctx.tech_stack else ""
        test_line = f"- **Test Framework:** {ctx.test_framework}" if ctx.test_framework else ""
        hosting_line = f"- **Hosting:** {ctx.hosting}" if ctx.hosting else ""

        tech_block = "\n".join(filter(None, [lang_line, framework_line, stack_line, test_line, hosting_line]))

        formatter_note = f"- Format code with `{ctx.formatter}` before committing." if ctx.formatter else ""
        linter_note = f"- Run `{ctx.linter}` and fix all warnings before completing a task." if ctx.linter else ""
        standards_block = "\n".join(filter(None, [formatter_note, linter_note]))

        project_type_guidance = self._get_project_type_guidance(ctx)
        claudeignore_note = self._get_ignore_patterns(ctx)

        purpose_block = ""
        if ctx.purpose or ctx.problem:
            parts = []
            if ctx.purpose:
                parts.append(f"**Purpose:** {ctx.purpose}")
            if ctx.problem:
                parts.append(f"**Problem:** {ctx.problem}")
            purpose_block = "\n".join(parts)

        return f"""# {ctx.project_name or "Project"} — Gemini CLI Configuration

> **Gemini CLI Tip:** Use `/memory show` to inspect loaded context.
> Run `/memory refresh` to reload after editing this file.
> Your 1M token context window is an advantage — use it for large codebase exploration.

## Project Overview
{purpose_block if purpose_block else f"- **Name:** {ctx.project_name or 'Project'}" }
- **Type:** {ctx.project_type or "general"}
- **Description:** {ctx.description or "No description provided."}

## Tech Stack
{tech_block if tech_block else "- Not specified. Infer from the codebase."}

## Development Standards
{standards_block if standards_block else "- Follow language best practices and conventions."}
- Write tests for new functionality.
- Keep functions small and focused — one responsibility per function.
- Prefer explicit over implicit.

{project_type_guidance}

## Context Management
This project uses Gemini CLI's large context window effectively:

- **Explore first:** Before making changes, read relevant files to understand existing patterns.
- **Trace dependencies:** Follow imports and function calls to understand impact of changes.
- **Large refactors:** Break into logical chunks; verify tests pass after each chunk.

## What NOT to Do
- Do not delete files without confirmation.
- Do not run `git push --force` without explicit instruction.
- Do not modify `.env` files or expose secrets.
- Do not install new dependencies without noting them.

## File Organization
{claudeignore_note}

---
*Generated by [vcsx](https://github.com/barancanercan/vcsx) — AI coding environment setup.*
*Tip: Add a global `~/.gemini/GEMINI.md` for cross-project defaults.*
"""

    def _get_project_type_guidance(self, ctx: ProjectContext) -> str:
        guidance_map = {
            "web": """## Web Project Guidance
- Keep components small and reusable.
- Separate business logic from UI components.
- Always handle loading, error, and empty states.
- API calls go in dedicated service files, not components.
""",
            "api": """## API Project Guidance
- Follow RESTful conventions: GET (read), POST (create), PUT/PATCH (update), DELETE.
- Always validate input and return meaningful error messages.
- Use HTTP status codes correctly.
- Document endpoints as you build them.
""",
            "data-pipeline": """## Data Pipeline Guidance
- Use chunked processing for large datasets — never load everything into memory.
- Log progress at meaningful intervals.
- Make pipelines idempotent: running twice should produce the same result.
- Validate data at ingestion boundaries.
- SQLite: always use `PRAGMA journal_mode=WAL` and `PRAGMA synchronous=OFF` for performance.
""",
            "cli": """## CLI Project Guidance
- Every command needs `--help` text.
- Exit codes: 0 = success, non-zero = failure.
- Print errors to stderr, data to stdout.
- Support `--dry-run` for destructive operations.
""",
            "library": """## Library Guidance
- Public API surface should be minimal and stable.
- Every public function needs a docstring.
- Semantic versioning: breaking changes = major bump.
- 100% test coverage for public API.
""",
        }
        return guidance_map.get(ctx.project_type, "")

    def _get_ignore_patterns(self, ctx: ProjectContext) -> str:
        base = ["node_modules/", "dist/", "build/", ".git/", ".env", "*.log"]
        lang_extras = {
            "python": ["__pycache__/", "*.pyc", ".venv/", "*.egg-info/", ".pytest_cache/", "coverage/"],
            "typescript": ["*.d.ts", ".next/", "coverage/", "*.tsbuildinfo"],
            "javascript": [".next/", "coverage/"],
            "java": ["target/", "*.class", "*.jar"],
            "go": ["vendor/", "*.exe"],
            "rust": ["target/"],
        }
        extras = lang_extras.get(ctx.language.lower(), []) if ctx.language else []
        ignore_list = "\n".join(f"  - `{p}`" for p in base + extras)
        return f"""Avoid reading these paths — they pollute context without adding value:
{ignore_list}

Consider creating a `.geminiignore` file (same format as `.gitignore`) if supported in your Gemini CLI version."""
